### PR TITLE
EDI export

### PR DESCRIPTION
**Pull request by phl0**
For the latest DARC contest in Germany I needed an export in .edi format. This implements a new function for that. It requires a suitable filter to be set beforehand. The export was tested succesfully while uploading the logs for the March VHF/UHF/SHF contest :)

### CODE REVIEW

**Comment by OH1KH** [comment]
Tested with some old 6m qsos.
I did not get far as I had no srx_strings, just locators.

 loc := UpperCase(dmData.Q.FieldByName('srx_string').AsString);

Should both be checked? If there is no srx_string then check if there is a loc entry instead?
Well, on the other hand I did not have srx, stx either with those qsos...

Should the export go through and mark bad parts with strings "ERROR" and give one combined report at the end?
Little bit same way as contest upload robots do show all errors at the end of upload so that they all can be fixed at one go.

That is just an idea. 
Not needed when contest is logged in right way using contest form.
With properly filled, filtered, log this works as it should. OK !

P.S.   there is a public function that check 4 and 6 chr locators to be valid:
function TfrmWorkedGrids.GridOK(Loc: string): boolean;

**Comment by phl0** [comment]
@OH1KH Thank you for your valuable feedback. 

From what I read in the contest rules is that the locator is a mandatory field. Thus I guess it just has to be in there. But I like the idea to let the export go through. But as the specs according to http://www.ok2kkw.com/ediformat.htm there is no flag to mark items as incomplete. So I will go for the option to just leave this entries out completely and spit out the callsigns of failed log entries afterwards.

The valdiation of locators will also be integrated.

**Comment by phl0** [comment]
Ok, first part is implemented. It should at least show an error message now saying that not all entries could be exported. Locator check and stuff to to come tomorrow.

**Comment by phl0** [comment]
Talked to @OH1KH. Will finish my changes and squash them to have it a single change for a new PR then. This one will be closed.

**Pull request closed without merging**
