### PR TITLE
Add all uWave bands and fix frequency display issue

### PR DESCRIPTION
**Pull request by sq6emm**
with current version apt-update is not working any longer - also added changes to alllow automagically configure tzdata

### CODE REVIEW

**Comment by sq6emm** [comment]
Resolves https://github.com/ok2cqr/cqrlog/issues/442

**Review by phl0 — CHANGES_REQUESTED** [review]
Shouldn't we at least add one more digit for 3-digit GHz frequencies if we are touchting the code? 😇

**Comment by sq6emm** [comment]
But no more!;) Working on adding all bands according to band plans, then it will be possible to test what you asked for;) Will message when done.

**Review by phl0 — APPROVED** [review]
Looks god now after tests. See https://github.com/ok2cqr/cqrlog/issues/442#issuecomment-931279796

**Comment by phl0** [comment]
I discovered an error with the new bands. The last entry for 240GHz is causing hickups on two of my Linux machines that I use CQRlog on:

Screenshot from 2021-10-04 12-06-32

Screenshot from 2021-10-04 12-07-24

All the bands before that were added without issues. Deleting 240GHz and re-adding it I can re-produce this error. Could someone verify this? I guess it is an overflow issue for a variable or the like.

**Comment by sq6emm** [comment]
Yeah... look's like lack of some variable. I had a lot of this issues while testing. I will take care of this.

**Comment by sq6emm** [comment]
Could you please describe what exactly are you doing?
For me Preferences->Bands tick/untick 241G even with restart in the middle works fine... ?

**Comment by phl0** [comment]
I added that band by hand to my mysql database and then startet CQRlog.

**Comment by sq6emm** [comment]
Would you mind double check?
I deleted .config/cqrlog and went from scratch... all works fine...
Would you provide me detailed steps to reproduce?
SQL insert query etc?

**Comment by phl0** [comment]
This is the SQL query:

'''
INSERT INTO `bands` (`id_bands`, `band`, `b_begin`, `b_end`, `cw`, `rtty`, `ssb`, `rx_offset`, `tx_offset`) VALUES (29, '1MM', '241000.0000', '248000.0000', '241000.0000', '248000.0000', '248000.0000', '0.0000', '0.0000');
'''

I will check with an empty .config/cqrlog.

**Pull request merged**
