### PR TITLE
DXChat new feature to DXCluster

### PR DESCRIPTION
**Pull request by OH1KH**
While new version of CQ-monitor is still under test I suggest this new feature to DXCluster.
Check CqrlogAdditions2.pdf (new version) last chapter DXChat for information.

This one was first completely new form, but I did not like it. Reason for new form for was jakoizmemo.pas that I could not understand. (Perhaps I should also use Finnish for comments, procedure, function and variable names to brighten up day :D :D )

Decided to make "a blind copy" of pnlTelnet and see if it works. I did it three times before it worked as should.
Now it seems to work as intended, looks good and is completely (almost: left 2px) hidden if needed.

### CODE REVIEW

**Comment by ok2cqr** [comment]
What is "dx chat"? Why we need a dx chat? Saku, again, one pull request one change, this one do three different things (revert CQ monitor, wkd before bold, dx chat)

**Comment by ok2cqr** [comment]
I just try it and the "dx chat" is on the top of the spot list. That is not good idea, if someone will have small dxcluster window, he will see only "dx chat" and nothing more.

**Comment by OH1KH** [comment]
Why:    No lost talks while away from PC. All saved and local time stamped from flood of DXSpots.
Top of spots:  RTFM!! It is adjustable and the minimum height is 2 pixels. Is that too much ?
One Pull:  GitHub made it again. No "rollback" possible. Looks like 3, but actually is just ONE pull req.

I do not know if mail I replied never went anywhere. (notifications@github) so put it short in here, too.

**Comment by ok2cqr** [comment]
I'm not sure if I want dx chat in CQRLOG. I've been licenced for almost 20 years and never needed that function.

Yes, it's one pull request and that is what I don't like. You have to commit and push one change, create pull request and do another change, that will work. I'll try to cherry pick commits related to CQ monitor.

**Comment by OH1KH** [comment]
Forget this

**Pull request closed without merging**
