### PR TITLE
Re-orer sequence of input fields in contest mode

### PR DESCRIPTION
**Pull request by phl0**
Seems like the tab order of input fields has experienced some randomness :).
This re-orders the tabs into a sequence that makes sense in my eyes. Should the original sequence be intended feel free to cancel this PR :)

### CODE REVIEW

**Comment by OH1KH** [comment]
HI !
Did  you notice that tab order changed depending selections?

1) If nothing is selected it is:
call -> NR r -> MSG r ->Save QSO  (that is all you need. In contest reports are always 599)

2) if tru (true reports) is selected:
call -> RST s -> RST r -> NR r -> MSG r ->Save QSO (this is mainly for qso pileup outside contest ES, TROPO or something, the question is should we skip NR r here ?)

3) if inc selected (qso counter) order is:
call -> NR r -> MSG r ->Save QSO  (else does not matter in contest)

4) Tru and inc selected (contest where true reports are given with number ? not worked any... :-) )
call -> RST s -> RST r -> NR r -> MSG r ->Save QSO 

Order that comes after listed sequences 1-4 is more or less random and meaningless tab order could be switched away from rest.

If I would change something I would:
case:
1) [leave NR r away]  contest with 599 + zone. But it is a question as we can have contest with fixed number (zone, age etc) and message. So I am not sure about leaving it from tab order...
2) [leave NR r away]  ES etc pileups do not need NR r, but see case 1) there might be cases it is needed.

In all cases disable other tab orders after reached ->Save QSO could be handy.
Discussion about Cancel... Should it come after Save qso tab order? I think it is not needed as you can cancel whole entry with 2xESC 
Actually I do not see any use for Cancel. 
In contest you do not use mouse, just keyboard and perhaps keyer (& PTT? if not having foot pedal) so tab order is important.

What ever is done, it must be done programmatically at all places (form show, checkbox change, save qso, cancel qso ) . Not by lfm changes.


Comments ?
(Ohh-....  Petr you did merge allready,  no good )

**Comment by phl0** [comment]
Hi Saku,
oh I agree. So I vote for unmerging my changes. Shall I do another PR for this?
vy73 de Florian DF2ET

**Comment by OH1KH** [comment]
I think it is now good time to check this through. I do not remember exactly how I did it then but I'm quite sure it can be done wiser and with shorter code.
Let's think a little bit. (Go through ideas , maybe some conversation... )
And then make revised pull request.

I do not remember exactly how I did it then, but now I think there should be a record of tab orders for cases Tru and Inc checked. It makes 0,0 - 1,0 - 0,1 and 1, 1 combinations so 4 sets for tab orders.
Form show and every change of those 2 checkbox and form contents clear with either 2xESC or QSO save should call tab order settings.

Only the line from callsign to qso save should have tab order. Others do not need it ( set tabOrder:=0, tabStop:=false)

Could you check this through keeping in mind what now have been said. I think it is better that someone else checks code first so that I do not repeat same errors that I might have done.
Then we see how it looks like from your point of view.

**Comment by phl0** [comment]
I appreciate the discussion. I did not notice that there was an order before. Apparently my docker machine broke down. I will try to fix this and re-evaluate the previous tab order of the contest log window.

**Pull request merged**
