### PR TITLE
Add UDP Log Uploader, based on N1MM+ XML format

### PR DESCRIPTION
**Pull request by kwirk**
This enables sending of `contactinfo`, `contactreplace` and `contactdelete` N1MM+ XML messages, via UDP, similar to N1MM+ and other loggers.

In order to implement the delete properly, the foreign key constraint on the `log_changes` table has been removed, such that the contact ID can still be generated.

The contact ID is currently based on the `cqrlog_main` table primary key, and logbook callsign.

### CODE REVIEW

**Comment by ok2cqr** [comment]
Could you rebase it to the current master, please? Thanks a lot.

**Comment by OH1KH** [comment]
Petr, it's in Alpha_119 PR already.

**Comment by OH1KH** [comment]
I found small bug from it. It is not fixed yet.
"If UPload QSO data immediately" is checked but after that "Enable sending UDP Log Messages" is UNchecked adding new qso will prompt in status window that "uploading should be enabled first"

I do not know do other uploads act same way. Just noticed that yesterday evening when used test log that has UDP upload on and I turned It off for other tests.

**Comment by ok2cqr** [comment]
Could you solve the conflicts, please? I have no idea how it should work. Could you give me some examples why the CQRLOG needs to receive the data from N1MM running on Windows?

**Comment by OH1KH** [comment]
As said in earlier message this PR was already added to Alpha_119 PR that you have committed.  No need to commit it again. 
It is not for receiving data from N1MM+, it produces same kind of export than N1MM that is used in some cloud log services. That is how I understood it from creator's explain.

If you create UDP listener you can see datagarm with qso data every time qso is logged.

**Comment by ok2cqr** [comment]
Thank you for explanation, Saku. I'm closing the pull requested.

**Pull request closed without merging**
