### PR TITLE
LoTW import bug when having multiple QSOs with same station on same band and day.

### PR DESCRIPTION
**Pull request by sm2vsd**
Hi! 
I was running my trusty old cqrlog v1.8.1 (time to upgrade huh? :) when I received LoTW qsls for contacts from the same station on same band but on different modes, only one of those QSOs got marked, and in the dialog that showed new QSOs it was registered as SSB but in the log the CW. Tried to find if there where a bug fix for this but when looking in the master branch the bug was still there. The problem is that when the code compares the time in the LoTW adif with the time in the log it uses the LoTW adif time in both places. When the call,band and day query is received it has multiple replies and the code picks the wrong one due to not using the correct time. This PR solves this, but there are more problems left, and I guess there are maybe some historical things why things are the way there are:

1. When comparing the time from the log and the LoTW adif time there are a window of +/-5min for a valid match. Why is that? 
The time you get from the LoTW adif is already matched (with the time-frame) with the corresponding qsl/qso, and the LoTW adif time received is the same time that you sent from your log when you uploaded it. Are there some corner-cases when the time is not expected to be the same?

2. When querying the DB for the calls matching the LoTW adif there is no MODE in the query, in the code there are code in comments regarding this. If we have two QSOs and different mode within the time-window mentioned above, or even with the same-time stamp it will probably mark only one QSO. Or maybe you only have LoTW QSL for one of the QSOs, it might mark the wrong one as confirmed.

So the best would be a full check with both time and mode to get it correct, but is there something I missed? Has there maybe been a problem with mode when FT8 was introduced?

The fix has been tested with both real data downloaded and processed from ARRL and from two mockup ADIFs to be sure that it would mark the correct QSO.

Since I had the questions above I settled to only make the changes that where first at hand to get it to work partly, and leave the rest for discussion.

Thanks by the way for great software!
73's de Jonas

### CODE REVIEW

**Comment by ok2cqr** [comment]
Hi Jonas,

thank you for the fix!

I don't remember why there is the adif tome comparsion :(. It has been long time from last modification.

I remember the debate about modes but we didn't find any solution yet. There was a problem with digital modes like PSK but I don't use digi modes and don't know how to solve it. If you have any solution, please let me know and/or send the pull request.

73 Petr

**Comment by sm2vsd** [comment]
Hi Petr!

Ok, I have some digi-modes in my log, I will do some investigation and see if I can track down any issues and also read up more about the time comparison.

Thanks!
73's de Jonas

**Comment by sm2vsd** [comment]
I have tried to find any previous discussions about the PSK issue but could not find any,  I made some investigations and my current findings are these after reading up on how LoTW wants its data. [https://lotw.arrl.org/lotw-help_devel_ru/submitting-qsos/](url)

LoTW accepts only valid formated ADIF files, and cqrlog has several modes that is not part of the ADIF spec. [http://www.adif.org.uk/304/ADIF_304.htm#Mode_Enumeration](url) 
One example is BPSK31, its in the drop down menu in cqrlog but its not a valid mode enumeration in the ADIF spec. The workaround from ARRL is to make a conversion/mapping in the TQSL software. (or some other editing software to manually/automatic change the mode) If one does that, converting the BPSK31 to PSK31 when signing and uploading to LoTW then when downloading the result to cqrlog again it will not match since LoTW has mode=PSK31 and cqrlog has mode=BPSK31.

The obvious is to make cqrlog follow the ADIF spec. and only allow valid modes in the dropdown menu, and if you add new modes, you are on your own. Another take would be to implement so that the modes internally in cqrlog has more properties to them, so that cqrlog does the correct translation to follow the ADIF spec. when exporting logs and also a reverse lookup when downloading the log.

Another route would be to let cqrlog know that BPSK31 is of LoTW (DATA) type and compare to that when downloading, but then you would have to make the "upload-conversion" outside of cqrlog.

In reality these things are really nitpicking :) but it would be fun to get it to work properly.

Are there any implications on deleting modes from the dropdown menu other than upset users? :)

**Comment by sm2vsd** [comment]
I have tried to find any previous discussions about the PSK issue but could not find any,  I made some investigations and my current findings are these after reading up on how LoTW wants its data. [https://lotw.arrl.org/lotw-help_devel_ru/submitting-qsos/](https://lotw.arrl.org/lotw-help_devel_ru/submitting-qsos/)

LoTW accepts only valid formated ADIF files, and cqrlog has several modes that is not part of the ADIF spec. [http://www.adif.org.uk/304/ADIF_304.htm#Mode_Enumeration](http://www.adif.org.uk/304/ADIF_304.htm#Mode_Enumeration) 
One example is BPSK31, its in the drop down menu in cqrlog but its not a valid enumeration in the ADIF spec. The workaround from ARRL is to make a conversion in the TQSL software. (or some other editing software to manually/automatic change the mode) If one does that, converting the BPSK31 to PSK31 when signing and uploading to LoTW then when downloading the result to cqrlog again it will not match since LoTW has mode=PSK31 and cqrlog has mode=BPSK31.

The obvious is to make cqrlog follow the ADIF spec. and only allow valid modes in the dropdown menu, and if you add new modes, you are on your own. Another take would be to implement so that the modes internally in cqrlog has more properties to them, so that cqrlog does the correct translation to follow the ADIF spec. when exporting logs and also a reverse lookup when downloading the log.

Another route would be to let cqrlog know that BPSK31 is of LoTW (DATA) type and compare to that when downloading, but then you would have to make the "upload-conversion" outside of cqrlog.

In reality these things are really nitpicking :) but it would be fun to get it to work properly.

**Pull request merged**
